id = "efmt"
name = "efmt"
description = "Erlang code formatter (efmt) language server"
version = "0.21.0"
schema_version = 1
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
repository = "https://github.com/sile/efmt"

[languages.erlang]
path = "languages/erlang/config.toml"

[language_servers.efmt-lsp]
name = "efmt LSP"
language = "Erlang"

[[capabilities]]
kind = "process:exec"
command = "efmt-lsp"
args = ["**"]
